import type { ReactNode } from "react";
import {
  TableView,
  Cell,
  Column,
  Row,
  TableBody,
  TableHeader,
} from "../indexLib";
import { useId } from "react-aria";

interface RowData {
  id: number;
  name: string;
  description: string;
  type: {
    name: string;
  };
  defaultValue: string;
  parent: {
    name: string;
  };
  required: boolean;
}

interface RowDataFinal {
  id: string;
  name: string;
  description: string;
  type: string;
  defaultValue: string;
  required: boolean;
}

/**
 * Table for React props generated by react-docgen
 *
 * @see https://github.com/episodeyang/react-component-props-table/
 */
const PropsTable = (props: { className: string; propMetaData: RowData[] }) => {
  const { propMetaData, ...rest } = props;
  let { className = "" } = props;
  if (className) className += " component-props-table";

  interface ColumnData {
    name: string;
    uid: keyof RowDataFinal;
  }

  const columns: ColumnData[] = [
    { name: "Prop Name", uid: "name" },
    { name: "Type", uid: "type" },
    { name: "isRequired", uid: "required" },
    { name: "Default Value", uid: "defaultValue" },
    { name: "Description", uid: "description" },
  ];

  const keys = Object.keys(propMetaData) as Array<keyof typeof propMetaData>;
  const rows = keys.map((key) => {
    const prop = propMetaData[key] as RowData;
    return {
      // eslint-disable-next-line react-hooks/rules-of-hooks
      id: useId(),
      name: prop?.name,
      description: prop?.description,
      defaultValue: prop?.defaultValue,
      type: prop?.type ? prop.type.name : "",
      required: prop?.required ? "required" : "optional",
    };
    // @todo ommission names make a lookup parsed in as config.
    // switch (prop?.parent?.name) {
    //   case "DOMAttributes":
    //   case "HTMLAttributes":
    //   case "AriaAttributes":
    //     return;
    //   default:
    //     return {
    //       id: useId(),
    //       name: prop?.name,
    //       description: prop?.description,
    //       defaultValue: prop?.defaultValue,
    //       type: prop?.type ? prop.type.name : "",
    //       required: prop?.required ? "true" : "false",
    //     };
    // }
  });

  return (
    <TableView
      aria-label="Example table with static contents"
      // selectionMode="multiple"
      vol={1}
      isResponsive
      {...rest}
    >
      <TableHeader columns={columns}>
        {(column) => (
          <Column key={column.uid} data-id="table-column">
            {column.name}
          </Column>
        )}
      </TableHeader>
      <TableBody items={rows}>
        {(item) => (
          <Row>
            {(columnKey) => {
              const value = item[columnKey as keyof RowDataFinal];
              let renderValue: string | ReactNode = value;
              if (columnKey === "name") {
                renderValue = (
                  <code style={{ color: "rgb(0 190 199)" }}>{value}</code>
                );
              }
              if (columnKey === "required") {
                renderValue =
                  value === "required" ? (
                    <span style={{ color: "rgb(255, 76, 34)" }}>{value}</span>
                  ) : (
                    <span style={{ color: "#c6c6c6" }}>{value}</span>
                  );
              }
              return <Cell data-id="table-cell">{renderValue}</Cell>;
            }}
          </Row>
        )}
      </TableBody>
    </TableView>
  );
};

export default PropsTable;
